name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - 
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry:
        username: paripuranam
        password: getenv('docker_password')
        ecr: 
        logout:
